module.exports = {
  Node            : require('./dist/class/Node.class.js').default,
  Document        : require('./dist/class/Document.class.js').default,
  DocumentFragment: require('./dist/class/DocumentFragment.class.js').default,
  Element         : require('./dist/class/Element.class.js').default,
  HTMLElement     : require('./dist/class/HTMLElement.class.js').default,
  HTMLMetaElement : require('./class/HTMLMetaElement.class.js'),
  HTMLOListElement: require('./class/HTMLOListElement.class.js'),
  HTMLUListElement: require('./class/HTMLUListElement.class.js'),
  HTMLDListElement: require('./class/HTMLDListElement.class.js'),
  HTMLLIElement   : require('./class/HTMLLIElement.class.js'),
  HTMLTableSectionElement: require('./class/HTMLTableSectionElement.class.js'),
  HTMLTableRowElement    : require('./class/HTMLTableRowElement.class.js'),
  HTMLAnchorElement: require('./dist/class/HTMLAnchorElement.class.js').default,
  HTMLDataElement    : require('./class/HTMLDataElement.class.js'),
  HTMLTimeElement    : require('./class/HTMLTimeElement.class.js'),
  HTMLTemplateElement: require('./class/HTMLTemplateElement.class.js'),
}
