module.exports = {
  Node                   : require('./dist/class/Node.class.js').default,
  Document               : require('./dist/class/Document.class.js').default,
  DocumentFragment       : require('./dist/class/DocumentFragment.class.js').default,
  Element                : require('./dist/class/Element.class.js').default,
  HTMLElement            : require('./dist/class/HTMLElement.class.js').default,
  HTMLMetaElement        : require('./dist/class/HTMLMetaElement.class.js').default,
  HTMLOListElement       : require('./class/HTMLOListElement.class.js'),
  HTMLUListElement       : require('./class/HTMLUListElement.class.js'),
  HTMLDListElement       : require('./dist/class/HTMLDListElement.class.js').default,
  HTMLLIElement          : require('./dist/class/HTMLLIElement.class.js').default,
  HTMLTableSectionElement: require('./class/HTMLTableSectionElement.class.js'),
  HTMLTableRowElement    : require('./class/HTMLTableRowElement.class.js'),
  HTMLAnchorElement      : require('./dist/class/HTMLAnchorElement.class.js').default,
  HTMLDataElement        : require('./dist/class/HTMLDataElement.class.js').default,
  HTMLTimeElement        : require('./dist/class/HTMLTimeElement.class.js').default,
  HTMLTemplateElement    : require('./dist/class/HTMLTemplateElement.class.js').default,
}
