module.exports = {
  Node                    : require('./dist/class/Node.class.js').default,
  Document                : require('./dist/class/Document.class.js').default,
  DocumentFragment        : require('./dist/class/DocumentFragment.class.js').default,
  Element                 : require('./dist/class/Element.class.js').default,
  HTMLElement             : require('./dist/class/HTMLElement.class.js').default,
  HTMLMetaElement         : require('./dist/class/HTMLMetaElement.class.js').default,
  HTMLOListElement        : require('./dist/class/HTMLOListElement.class.js').default,
  HTMLUListElement        : require('./dist/class/HTMLUListElement.class.js').default,
  HTMLDListElement        : require('./dist/class/HTMLDListElement.class.js').default,
  HTMLLIElement           : require('./dist/class/HTMLLIElement.class.js').default,
  HTMLTableSectionElement : require('./dist/class/HTMLTableSectionElement.class.js').default,
  HTMLTableRowElement     : require('./dist/class/HTMLTableRowElement.class.js').default,
  HTMLTableCellElement    : require('./dist/class/HTMLTableCellElement.class.js').default,
  HTMLAnchorElement       : require('./dist/class/HTMLAnchorElement.class.js').default,
  HTMLDataElement         : require('./dist/class/HTMLDataElement.class.js').default,
  HTMLTimeElement         : require('./dist/class/HTMLTimeElement.class.js').default,
  HTMLTemplateElement     : require('./dist/class/HTMLTemplateElement.class.js').default,

  Component : require('./dist/class/_Component.class.js').default,
}
